### ISSUE TITLE
Epic: Bench GTM

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#10]
```[tasklist]
### Prerequisites
- [ ] https://github.com/grafana/hosted-grafana/issues/4519
- [ ] https://github.com/grafana/grafana-bench/issues/14
- [ ] https://github.com/grafana/grafana-bench/issues/11
- [ ] https://github.com/grafana/grafana-bench/issues/24
- [ ] https://github.com/grafana/grafana-bench/issues/12
- [ ] https://github.com/grafana/grafana-bench/issues/13
- [ ] https://github.com/grafana/hosted-grafana/issues/4535
- [ ] https://github.com/grafana/grafana-bench/issues/16
- [ ] https://github.com/grafana/grafana-bench/issues/41
- [ ] https://github.com/grafana/grafana-bench/issues/46
- [ ] https://github.com/grafana/grafana-bench/issues/40
- [ ] https://github.com/grafana/grafana-bench/issues/15
- [ ] https://github.com/grafana/grafana-bench/issues/25
- [ ] https://github.com/grafana/grafana-bench/issues/18
- [ ] https://github.com/grafana/grafana-bench/issues/19
- [ ] https://github.com/grafana/grafana-bench/issues/20
- [ ] https://github.com/grafana/grafana-bench/issues/21
- [ ] https://github.com/grafana/grafana-bench/issues/23
```

**Future (ideas)**
```[tasklist]
### Future
- [x] calculate average time for various tests
- [x] convert fmt.Print statements use slog package
```
