### ISSUE TITLE
Add support for test run drivers

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#117]
Presently the test runner relies on `k6` command for running tests. 

There are different scenarios in which it would be convenient to delegate the execution to other "test execution drivers":
- running tests that use other testing tools like playwright
- running tests using an image that contains all the dependencies of the testing tool (e.g. k6 and chromium for browser tests)

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-bench/issues/184
- [ ] https://github.com/grafana/grafana-bench/issues/188
- [ ] implement a docker test driver that delegates test execution to an image
- [ ] https://github.com/grafana/grafana-bench/issues/200
```
