### ISSUE TITLE
Verify logger output for dashboards

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#119]
Cross reference log output used in dashboards with new log output in the test runner. 

Make sure we're not missing any attributes

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-bench/issues/177
- [ ] https://github.com/grafana/grafana-bench/issues/178
- [ ] https://github.com/grafana/grafana-bench/issues/181
```
