### ISSUE TITLE
Milestone 1.1: Document and deliver a comprehensive strategy for testing Grafana

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#132]
```[tasklist]
- [ ] https://github.com/grafana/grafana-bench/issues/112
- [x] https://github.com/grafana/grafana-bench/issues/93
- [x] https://github.com/grafana/grafana-bench/issues/87
- [x] https://github.com/grafana/grafana-bench/issues/88
- [ ] https://github.com/grafana/grafana-bench/issues/86
- [ ] https://github.com/grafana/grafana-bench/issues/140
- [ ] Distribute Grafana Testing Strategy
```
