### ISSUE TITLE
Milestone 1.2: Develop baseline performance for Grafana based on the Google deal requirements

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#133]
https://docs.google.com/document/d/1dNeEihwAoieujVOWWtl9M9XzJSkeveaj4Sa8iOc9T6g/edit

```[tasklist]
- [x] Setup dedicated instance for load testing with dedicated SQL database
- [x] https://github.com/grafana/grafana-bench/issues/138
- [ ] https://github.com/grafana/grafana-bench/issues/113
- [x] https://github.com/grafana/grafana-bench/issues/137
- [ ] https://github.com/grafana/grafana-bench/issues/146
- [ ] https://github.com/grafana/grafana-bench/issues/147
- [ ] https://github.com/grafana/grafana-bench/issues/293
- [ ] Dashboard for monitoring performance during test
- [ ] Which repository should these tests live in?
- [ ] Dashboard for load suite runs
- [ ] User simulator which exercises existing k6 scenarios in parallel and concurrently
- [x] Strip down https://github.com/grafana/k6-tests-for-inditex into dashboard / user data
- [x] Figure out mechanism for executing tests (what was this?)
- [ ] https://github.com/grafana/grafana-bench/issues/256
```
