### ISSUE TITLE
Milestone 1.3: Deliver a stable Bench test runner

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#134]
```[tasklist]
### Test Runner
- [ ] https://github.com/grafana/grafana-bench/issues/99
- [ ] https://github.com/grafana/grafana-bench/pull/106
- [ ] https://github.com/grafana/grafana-bench/issues/98
- [ ] https://github.com/grafana/grafana-bench/issues/109
- [ ] https://github.com/grafana/grafana-bench/issues/124
- [ ] https://github.com/grafana/grafana-bench/issues/107
- [ ] https://github.com/grafana/grafana-bench/issues/155
```

```[tasklist]
###  Baseline checks for Hosted Grafana Plugins
- [ ] https://github.com/grafana/grafana-bench/issues/174
- [ ] https://github.com/grafana/grafana-bench/issues/175
- [ ] https://github.com/grafana/grafana-bench/issues/182
```

```[tasklist]
### Rollout bench test runner and clean up
- [ ] https://github.com/grafana/grafana-bench/issues/116
- [ ] https://github.com/grafana/grafana-bench/issues/119
- [ ] https://github.com/grafana/grafana-bench/issues/163
- [ ] https://github.com/grafana/grafana-bench/issues/178
- [ ] https://github.com/grafana/grafana-bench/issues/162
- [ ] https://github.com/grafana/grafana-bench/issues/108
- [ ] https://github.com/grafana/grafana-bench/issues/165
- [ ] https://github.com/grafana/grafana-bench/issues/191
- [ ] https://github.com/grafana/grafana-bench/issues/164
- [ ] https://github.com/grafana/grafana-bench/issues/195
- [ ] https://github.com/grafana/grafana-bench/issues/196
- [ ] https://github.com/grafana/grafana-bench/issues/201
- [ ] https://github.com/grafana/grafana-bench/issues/203
- [ ] https://github.com/grafana/grafana-bench/issues/125
- [ ] https://github.com/grafana/grafana-bench/issues/115
- [ ] https://github.com/grafana/grafana-bench/issues/141
- [ ] https://github.com/grafana/grafana-bench/issues/118
- [ ] https://github.com/grafana/grafana-bench/issues/193
- [ ] https://github.com/grafana/grafana-bench/issues/194
- [ ] https://github.com/grafana/grafana-bench/issues/199
- [ ] https://github.com/grafana/grafana-bench/issues/208
- [ ] https://github.com/grafana/grafana-bench/issues/213
- [ ] https://github.com/grafana/grafana-bench/issues/259
- [ ] https://github.com/grafana/grafana-bench/issues/279
- [ ] https://github.com/grafana/grafana-bench/issues/280
- [ ] https://github.com/grafana/grafana-bench/issues/285
```
```[tasklist]
### Public Release
- [ ] https://github.com/grafana/grafana-bench/issues/160
- [ ] https://github.com/grafana/grafana-bench/issues/165
- [ ] https://github.com/grafana/grafana-bench/issues/125
- [ ] https://github.com/grafana/grafana-bench/issues/164
- [x] Demo for K6 Team
- [ ] Record video on how Bench works
- [ ] Record tutorial on how to write tests for Grafana
- [ ] Tuesday Demo + training (separate for K6?)
- [ ] Announcement
- [ ] Release day!
```

```
