### ISSUE TITLE
Figure out a mechanism for running bench job against an instance of Grafana without leaking secrets in Drone Job

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#150]
We have all the pieces in place to execute a test run against an instance of Grafana, however, we're leaking secrets through the logs. We need to figure out a mechanism to provide those secrets to the job without leaking them.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-bench/issues/150
- [ ] Get local gcom dev + gcom credentials setup
- [ ] Figure out paradigm for creating secrets in vault
- [ ] Pass secret key to Argo workflow to retrieve Grafana Instance credentials
- [ ] Check if password auth is enabled
- [ ] Document how to run Bench against an instance
```
