### ISSUE TITLE
Milestone 1.3.3: Public Release

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#159]
Preparation to distribute the runner around Grafana

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-bench/issues/160
- [ ] https://github.com/grafana/grafana-bench/issues/165
- [ ] https://github.com/grafana/grafana-bench/issues/125
- [ ] https://github.com/grafana/grafana-bench/issues/164
```
(issue adding this to task list. completed) https://github.com/grafana/grafana-bench/issues/165
