### ISSUE TITLE
grafana-api-tests: patch support for GRAFANA_URL + GT_URL style environment variables

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#161]
Names in grafana-api-tests repo should be standardized. The repo was created using `GT_URL`. I really don't like this naming scheme and it doesn't feel obvious to me.

Let's move this over to a more explicit naming convention `GRAFANA_{key}`

```[tasklist]
### Tasks
- [ ] find/replace all references to GT_URL
- [ ] find/replace all references to GT_USERNAME
- [ ] Update docs https://github.com/grafana/grafana-api-tests/tree/main?tab=readme-ov-file#common-environment-variables
```
