### ISSUE TITLE
Fix docker file to package runner

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#162]
Refactor https://github.com/grafana/grafana-api-tests/blob/main/Dockerfile to do build steps necessary for new `bench test` command and remove unused variables

```[tasklist]
### Tasks
- [x] verify we're using the correct base container
- [x] remove `ENV_COMPILED_TESTS`
- [x] remove `ENV TEST_PATH`
- [x] verify tests are in the correct place
```
