### ISSUE TITLE
Grafana Testing Strategy Milestone 2: Beta Release

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#169]
```[tasklist]
### Project
- [ ] https://github.com/grafana/grafana-bench/issues/170
- [x] Add reporting automation to Grafana-Bench repo
- [ ] https://github.com/grafana/grafana-bench/issues/312
- [ ] https://github.com/grafana/grafana-bench/issues/308
- [ ] https://github.com/grafana/grafana-bench/issues/136
- [ ] grafana/grafana-bench#145
- [ ] CFP for R&D Offsite - Load Testing
- [ ] CFP for R&D Offsite - Grafana Bench
```
```[tasklist]
### Test Runner
- [ ] https://github.com/grafana/grafana-bench/issues/258
- [ ] https://github.com/grafana/grafana-bench/issues/286
- [ ] https://github.com/grafana/grafana-bench/issues/247
- [ ] https://github.com/grafana/grafana-bench/issues/318
- [ ] https://github.com/grafana/grafana-bench/issues/224
- [ ] https://github.com/grafana/grafana-bench/issues/320
- [ ] https://github.com/grafana/grafana-bench/issues/326
- [ ] https://github.com/grafana/grafana-bench/issues/327
- [ ] https://github.com/grafana/grafana-bench/issues/329
```

```[tasklist]
### API-Tests
- [ ] https://github.com/grafana/grafana-bench/issues/161
- [ ] https://github.com/grafana/grafana-bench/issues/215
- [ ] https://github.com/grafana/grafana-bench/issues/216
- [ ] https://github.com/grafana/grafana-api-tests/issues/397
```
```[tasklist]
### Improve Dashboard
- [ ] https://github.com/grafana/grafana-bench/issues/307
- [ ] https://github.com/grafana/grafana-bench/issues/234
- [ ] https://github.com/grafana/grafana-bench/issues/235
- [ ] https://github.com/grafana/grafana-bench/issues/319
```

```[tasklist]
## Documentation
- [ ] Remove references to ghcr in docs now that GAR image is public
- [ ] Video walkthrough on api test suite
- [ ] https://github.com/grafana/grafana-bench/issues/237
- [ ] https://github.com/grafana/grafana-bench/issues/284
- [ ] https://github.com/grafana/grafana-bench/issues/283
- [ ] https://github.com/grafana/grafana-bench/issues/221
- [ ] https://github.com/grafana/grafana-bench/issues/252
- [ ] https://github.com/grafana/grafana-bench/issues/251
- [ ] https://github.com/grafana/grafana-bench/issues/168
```
```[tasklist]
### Browser test support
- [ ] https://github.com/grafana/grafana-bench/issues/230
- [ ] https://github.com/grafana/grafana-api-tests/issues/136
- [ ] https://github.com/grafana/grafana-bench/issues/325
```

```[tasklist]
### Google Performance Baselines (track work in grafana-org#109)
- [ ] https://github.com/grafana/grafana-org/issues/109
- [ ] https://github.com/grafana/grafana-bench/issues/309
```

```[tasklist]
### RRC (track work in grafana-org issues)
- [x] Create job in RRC workflow for running experimental tests
- [ ] https://github.com/grafana/grafana-org/issues/95
- [ ] https://github.com/grafana/grafana-org/issues/94
- [ ] https://github.com/grafana/grafana-bench/issues/330
- [ ] https://github.com/grafana/grafana-bench/issues/334
```
