### ISSUE TITLE
Obtain an inventory of plugins installed in a hosted grafana instance

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#174]
Obtain a list of the plugins installed in a hosted grafana instance via a API that could be implemented in a k6 tes library

One important consideration is that any credentials required to access it should be available from a CI pipeline.
```[tasklist]
### Tasks
- [ ] Figure out api end point to verify a plugin exists
- [ ] Test that loops over the provisioned plugins and verifies they're all installed
- [ ] Test that loops over the user-installed plugins and verifies they're all installed
```
