### ISSUE TITLE
QA on rest of the test suite

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#19]
Review other tests in the test suite and see if we need to fix organization of existing tests
```[tasklist]
### Tasks
- [x] Get all tests converted to Typescript
- [x] Consolidate HG tests into single file / folder
- [x] Remove jsdoc annotations?
- [x] Audit each test in the suite
```
