### ISSUE TITLE
Run Bench against multiple architectures and build configurations

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#197]
Currently Bench is only run against Hosted Grafana builds in the Rolling Release Channels.

With Bench being cross-platform, we can add a lot of value by running the same tests against other common builds and architectures like OSS on raspi.

```[tasklist]
### Tasks
- [ ] Research our most common build configurations and platform architectures
- [ ] Create a pipeline for each architecture and build artifact
- [ ] Figure out where to report outcomes
```
