### ISSUE TITLE
Link to Grafana instance logs from suite / test run dashboard

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#212]
Add a panel to [test runs dashboard](https://ops.grafana-ops.net/d/d3381df1-fa32-4955-994a-e6a8bca58025/test-runs?&var-SuiteRun=smoke-19:34:57-api-tests-014d65e-graf-11.1.0-68872&from=1709498495459&to=$__tohttps://ops.grafana-ops.net/d/d3381df1-fa32-4955-994a-e6a8bca58025/test-runs?var-SuiteRun=smoke-19:34:57-api-tests-014d65e-graf-11.1.0-68872&from=1708889376610&to=1711477776611&orgId=1&var-ArgoWorkflow=grafana-instant-jmx4d&var-slug=k6testinstant6.grafana.net) which gets the grafana logs for the instance.

I have a variable plumbed, however, I now need to select the datasource based on the url of the instance and verify.

```[tasklist]
### Tasks
- [x] Add variable to dashboard
- [x] Add variable value in link from test runs
- [x] add panel to dashboard
- [x] select datasource based on slug url
```
