### ISSUE TITLE
Move `grafana-bench` images to GAR

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana-bench#222]
Move images to GAR. We can use https://github.com/grafana/shared-workflows/tree/main/actions/push-to-gar-docker.

```[tasklist]
### Tasks
- [x] Create service account and repositories in deployment tools. [Example](https://github.com/grafana/deployment_tools/tree/master/terraform/repositories/incident), [README](https://github.com/grafana/deployment_tools/blob/master/terraform/repositories/README.md).
- [x] Modify [.github/workflows/ci.yaml](https://github.com/grafana/grafana-bench/blob/main/.github/workflows/ci.yaml#L73) to use shared workflow.
- [ ] https://github.com/grafana/grafana-bench/issues/228
```
