### ISSUE TITLE
Create a quick guide for running tests with bench

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#237]
```[tasklist]
### Tasks
- [ ] Run tests using docker image (bench and api tests)
- [ ] running tests using bench image and tests from another repo
- [ ] https://github.com/grafana/grafana-bench/issues/297
- [ ] Document env variables
- [ ] .env file workflow
```
