### ISSUE TITLE
[Epic] Access Control performance and regression testing

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#309]
As a part of work on access control performance improvements, we need to understand how it performs after changes we introduce to see and evaluate improvements and identify regression. it's related to https://github.com/grafana/identity-access-team/issues/523. In a perfect scenario, we want to be able to compare performance of specific PR against main branch and get alerts in case of regression.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-bench/issues/311
- [ ] https://github.com/grafana/grafana-bench/issues/310
- [ ] Define a baseline grafana scale to run load tests against (ie 100K dashboards/1K users).
- [ ] Define target metrics to setup alerts on (ie, _dashboard search p95 is slower than 500 ms_).
- [ ] Figure out a way to automate Grafana instance spin up for load tests (probably, https://github.com/grafana/grafana-bench).
- [ ] Define a way to automate load testing using **k6** (https://github.com/grafana/grafana-api-tests is a good candidate)
- [ ] https://github.com/grafana/identity-access-team/issues/687
- [x] Define and write acceptance ("smoke") tests for critical access control parts.
- [ ] Build dashboards.
- [ ] Setup alerts.
```

```[tasklist]
### Optional
- [ ] Be able to run load tests for specific PR to compare with baseline.
```

## Notes

There's a project [grafana-api-tests](https://github.com/grafana/grafana-api-tests) that aims the same goal, it's a kind of framework for writing k6 tests for grafana and run it. It has 2 types of tests: **acceptance tests** and **benchmarks**. It's running in prod with [grafana-bench](https://github.com/grafana/grafana-bench) tool which is basically a helper for automating things around tests. it's very similar approach to what I do with [grafana-fake-users-generator](https://github.com/grafana/grafana-fake-users-generator), so we can use those tools to automate test environment. 

We can also significantly improve security and catch bugs earlier by creating set of **acceptance** (aka "smoke") tests, which are much closer to real-life scenarios than unit tests.
