### ISSUE TITLE
Grafana Load Test Performance Enhancements

### ISSUE THREAD

**Issue by mildwonkey** [grafana/grafana-bench#314]
Part of https://github.com/grafana/grafana-org/issues/109 - identify and implement performance enhancements using our "google sized" load test infrastructure.

```[tasklist]
### Tasks 
- [ ] Query & Table Tuning
- [ ] Database Tuning
- [ ] Other code enhancements (for e.g.: look into frequency of user_last_seen updates; local caching; remove unneeded transactions when a session will suffice)
- [ ] https://github.com/grafana/grafana-bench/issues/328
```
