### ISSUE TITLE
Add Bench Pipeline support to rolling release channels

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#330]
```[tasklist]
### Tasks
- [ ] Jsonnet lib to generate steps based on manifest of test suites
- [ ] get hosted-grafana-bench-cd argo workflow working in order to test jsonnet
- [ ] configure bench github app for `bench test` to access internal repos
```
