### ISSUE TITLE
[EPIC] Remove grafana-api-test image

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#340]
Stop generating an image with bench + grafana-api-tests. Run tests in RRC using grafana-bench image. Checkout tests referencing a specific release tag.

```[tasklist]
### Tasks
- [ ] Setup github app and grant permissions for accessing grafana-api-test repository
- [ ] Remove Jeff's personal token from RRC setup
- [ ] Disable api-test image build CI jobs
- [x] Use bench image in api-test CI for testing release
- [x] Update RRC libsonet to use bench image for running bench tests
```
