### ISSUE TITLE
Grafana Bench Milestone 3: Rollout

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#341]
```[tasklist]
### Dissemination and Adoption
- [ ] https://github.com/grafana/grafana-bench/issues/136
- [ ] https://github.com/grafana/grafana-api-tests/issues/396
- [ ] https://github.com/grafana/grafana-bench/issues/356
```

```[tasklist]
### Test Runner
- [ ] https://github.com/grafana/grafana-bench/issues/286
- [ ] https://github.com/grafana/grafana-bench/issues/318
- [ ] https://github.com/grafana/grafana-bench/issues/224
- [ ] https://github.com/grafana/grafana-bench/issues/320
- [ ] https://github.com/grafana/grafana-bench/issues/326
- [ ] https://github.com/grafana/grafana-bench/issues/327
- [ ] https://github.com/grafana/grafana-bench/issues/345
- [ ] https://github.com/grafana/grafana-bench/issues/361
- [ ] https://github.com/grafana/grafana-bench/issues/362
- [ ] https://github.com/grafana/grafana-bench/issues/363
- [ ] https://github.com/grafana/grafana-bench/issues/366
- [ ] https://github.com/grafana/grafana-bench/issues/369
- [ ] https://github.com/grafana/grafana-bench/issues/371
- [ ] https://github.com/grafana/grafana-bench/issues/355
- [ ] https://github.com/grafana/grafana-bench/issues/336
- [ ] https://github.com/grafana/grafana-bench/issues/376
- [ ] https://github.com/grafana/grafana-bench/issues/388
- [ ] https://github.com/grafana/grafana-bench/issues/389
```

```[tasklist]
### API-Tests
- [ ] https://github.com/grafana/grafana-bench/issues/161
- [ ] https://github.com/grafana/grafana-api-tests/issues/397
```
```[tasklist]
### Improve Dashboard
- [ ] https://github.com/grafana/grafana-bench/issues/307
- [ ] https://github.com/grafana/grafana-bench/issues/234
- [ ] https://github.com/grafana/grafana-bench/issues/235
- [ ] https://github.com/grafana/grafana-bench/issues/319
- [ ] https://github.com/grafana/grafana-bench/issues/370
- [ ] https://github.com/grafana/grafana-bench/issues/374
```

```[tasklist]
## Documentation
- [ ] Remove references to ghcr in docs now that GAR image is public
- [ ] Video walkthrough on api test suite
- [ ] https://github.com/grafana/grafana-bench/issues/237
- [ ] https://github.com/grafana/grafana-bench/issues/284
- [ ] https://github.com/grafana/grafana-bench/issues/283
- [ ] https://github.com/grafana/grafana-bench/issues/221
- [ ] https://github.com/grafana/grafana-bench/issues/252
- [ ] https://github.com/grafana/grafana-bench/issues/251
```
```[tasklist]
### Browser test support
- [ ] https://github.com/grafana/grafana-bench/issues/325
```

```[tasklist]
### RRC (track work in grafana-org issues)
- [ ] https://github.com/grafana/grafana-org/issues/95
- [ ] https://github.com/grafana/grafana-bench/issues/340
- [ ] https://github.com/grafana/grafana-bench/issues/350
- [ ] https://github.com/grafana/grafana-bench/issues/367
```
