### ISSUE TITLE
Grafana Bench Milestone 4: GA

### ISSUE THREAD

**Issue by pablochacin** [grafana/grafana-bench#411]
## Goal: Make grafana bench available for the grafana engineering organization
- [x] Complete developer documentation
- [x] Support for github actions
- [x] https://github.com/grafana/grafana-bench/issues/421
- [x] #469
- [x] #467
- [x] https://github.com/grafana/grafana-bench/issues/465
- [ ] Add link to dashboards in documentation

## Tasks

- [x] https://github.com/grafana/grafana-bench/issues/377
- [x] https://github.com/grafana/grafana-bench/issues/410
- [x] https://github.com/grafana/grafana-bench/issues/413
- [x] https://github.com/grafana/grafana-bench/issues/432
- [x] https://github.com/grafana/grafana-bench/issues/435
- [x] https://github.com/grafana/grafana-api-tests/issues/319
- [x] change path to vault secrets from hackathon-benchmark-k6-credentials to grafana-bench-rrc
