### ISSUE TITLE
Grafana Testing Strategy Milestone 1: Alpha Release

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#83]
```[tasklist]
### Milestone 1
- [ ] https://github.com/grafana/grafana-bench/issues/132
- [ ] https://github.com/grafana/grafana-bench/issues/133
- [ ] https://github.com/grafana/grafana-bench/issues/134
- [ ] Security Audit + OSS repo
- [ ] https://github.com/grafana/grafana-bench/issues/299
```
