### ISSUE TITLE
Grafana Testing Strategy

### ISSUE THREAD

**Issue by jalevin** [grafana/grafana-bench#86]
Create a document explaining our vision, reasoning, and strategy for testing Grafana as a holistic platform.

```[tasklist]
### Tasks
- [x] Problem statement
- [x] Types of tests
- [x] Centralized test repo architecture
- [ ] Spin off implementation from vision
```
